### ISSUE TITLE
uSync content import bug with umbracoUrlName property

### ISSUE THREAD

**Issue by TomSteer** [KevinJump/uSync3.0#95] opened 2016-11-08 12:11 UTC
Hey,
We have set the umbracoUrlName property on our root node to "/" so you can no longer get to it from both "/" & "/RootNodeName". However when usync export/imports content from under this node it seems to recreate it at the umbraco content root, rather than under the home node.
Thanks,
Tom

**Comment by KevinJump** [comment] 2017-05-22 13:40
I think this was actually caused by the same issue as in #112 - fixed in [Milestone 15](https://github.com/KevinJump/uSync/milestone/15) - [v3.3.1 release in feburary](https://github.com/KevinJump/uSync/releases/tag/5.6.1%2F3.3.1)

**Closed as completed by KevinJump** 2017-05-22 13:40 UTC
